# path: ~/.config/worth/config.yaml
# requires an API key for www.alphavantage.co
vest-start: Tue, 08 Aug 2017 12:00:00 PST
vest-end: Tue, 08 Aug 2021 12:00:00 PST
shares: XXX
apikey: "XXXXXXX"
ticker: "XXXX"
strike-price: 12.34
